### ISSUE TITLE
[BUG]使用的中华人民共和国地图缺少藏南地区

### ISSUE THREAD

**Issue by tyk1304245946** [Jiaocz/UMAP#5]
藏南地区自古是中华人民共和国的固有领土，虽然实际被印度控制但中国地图上应该加入，以免出现不必要的政治问题。

![Uploading Screenshot_2022-07-21-15-48-47-007_com.android.browser.jpg…]()

**Comment by Jiaocz** [comment]
请给出正确地图svg后会修改，开始项目时并没有找到省份划分清晰的svg地图。
